package Utils;

import org.apache.log4j.*;

public class Log {
   public static Logger log=Logger.getLogger(Log.class.getName());
 //when the test starts I should print the logs
    // when my test stops I should print the log
    //If I want to print any message in between I should print the logs
    public static void startTestCase(String testCaseName){
        log.info("*****************");
        log.info("*****************");
        log.info(" "+testCaseName+ "********************");

    }
    public static void endTestCase(String testCaseName){
        log.info("###################");
        log.info("###################");
        log.info(" "+testCaseName+ "##################");
    }
    public static void info(String message){
        log.info(message);

    }
    public static void warning(String warning){
        log.info(warning);

    }

    //Maven Life Cycle
    // clean -removes all the files generated by previous build
    //validate - checks the project is correct and all necessary info is available
    //compile -compiles the source code of the  project
    // test - runs the test for the project(when you run it  will happen lone with clean, validate and compile)
    //package -packages your compile code into a distributable format, such as JAR(captures) or WAR(helps you convert and keep info on server) files
    //verify - runs and checks on results of integration tests to ensure quality criteria is met
    // install -installs the package into local repository(everytime we add dependencies to POM these dependencies are add to our system as well, they are stored on computer inside folder ".m2")
    //site - generates documentation for the project
    //deploy - copies the final package to remote repository for sharing with other developers or projects


}
